### ISSUE TITLE
Как решить эту проблему?

### ISSUE THREAD

**Issue by Doglia** [HiddenCodeDevs/BlumTelegramBot#16]
Добрый вечер. Подскажите, как исправить данную ошибку? Благодарю
![image](https://github.com/user-attachments/assets/5ead6d67-f30c-4d85-8300-78bda4b25b54)

**Comment by 6zxa9** [comment]
перепроверь настройку points

**Comment by Doglia** [comment]
> перепроверь настройку points

с поинтами вроде разобрался. теперь не могу ввести API_ID и API_HASH. заблюрил их на скрине. не подскажешь, как эту хрень решить?
![cmd_9MIH6UL4bK](https://github.com/user-attachments/assets/5a542dc9-6df4-4e82-b54c-1313a982e52c)

**Comment by AlexKrutoy** [comment]
вместо env-example редачь env - копию example
