### ISSUE TITLE
Login error 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by vstri** [HiddenCodeDevs/BlumTelegramBot#17]
Login error 'NoneType' object has no attribute 'get'
![image](https://github.com/user-attachments/assets/5270d7dc-5e4f-433b-9619-ea98b2afa4c3)
Everything was working well but now faced with this issue

**Comment by XPacL** [comment]
Розрабы блума чето там нахуевертили, нужен фиксить код бота

**Comment by ForsakenBob** [comment]
Same problem, waiting for update
