### ISSUE TITLE
The proxy does not work, please optimize it.

### ISSUE THREAD

**Issue by LM88LM** [HiddenCodeDevs/BlumTelegramBot#24]
The proxy does not work, please optimize it and explain the proxy settings in detail in the README. Unable to connect to the network when setting up the session.
![screenshot-20240912-205549](https://github.com/user-attachments/assets/72a8f152-7a8e-4d1e-93ee-653a84aea944)

**Comment by LM88LM** [comment]
I use WSL and set the proxy to: https://127.0.0.1:20171, but I can't connect. Other scripts can

**Comment by LM88LM** [comment]
Can I just enter the proxy settings when creating an account? This is how I set up the Hamster Fighting Game script I used before.

**Comment by LM88LM** [comment]
![screenshot-20240912-213402](https://github.com/user-attachments/assets/8da8a433-65d8-46ac-8f37-baa37b803759)

**Comment by AlexKrutoy** [comment]
breh
