### ISSUE TITLE
2024-09-24 10:41:34 | SUCCESS | new2 | Logged in successfully ...... and freeeez

### ISSUE THREAD

**Issue by richMovvver** [HiddenCodeDevs/BlumTelegramBot#38]
Hi.
All accounts stopped after "Logged in successfully", is there a solution to this problem? Until today everything worked without errors. Thank you.

**Comment by mohammadabdi75** [comment]
Hello, have you put a Ref link in the .evo file?

**Comment by mohammadabdi75** [comment]
> Hi. All accounts stopped after "Logged in successfully", is there a solution to this problem? Until today everything worked without errors. Thank you.

Hello, have you put a Ref link in the .evo file?

**Comment by datboycode** [comment]
I've updated the code in my repo to fix the blum update issue

**Comment by AlexKrutoy** [comment]
fixed
