### ISSUE TITLE
Не запускается бот. Relogin

### ISSUE THREAD

**Issue by Kromaliy** [HiddenCodeDevs/BlumTelegramBot#39]
Проблема с запуском бота, пишет все время Relogin. Бот работал нормально, но что-то произошло.
Пробовал менять сервер, прокси, по новой устанавливать бот. Аккаунты живые, в чем может быть проблема?

**Comment by Bblkqq** [comment]
++ подтверждаю

**Comment by datboycode** [comment]
I've updated the code in my repo to fix the blum update issues

**Comment by Kromaliy** [comment]
> I've updated the code in my repo to fix the blum update issues

А что именно ты сделал чтоб заработал бот?

**Comment by AlexKrutoy** [comment]
fixed
