### ISSUE TITLE
Помогите пожалуйста разобраться

### ISSUE THREAD

**Issue by Litva63** [HiddenCodeDevs/BlumTelegramBot#43]
![1](https://github.com/user-attachments/assets/49e7a3fa-f173-4361-b7da-7c01ffb68e06)

**Comment by Litva63** [comment]
Добавил сессии и индивидуальные прокси, равное по числу сессий, бот вылетает

**Comment by Litva63** [comment]
![2](https://github.com/user-attachments/assets/83305ef5-85f4-4acc-b746-fbc3f56bada9)
![3](https://github.com/user-attachments/assets/e463718e-566e-41f1-a5a9-31b0b67d7f10)

**Comment by Litva63** [comment]
Без прокси все работает, но хотелось бы более качественную настройку

**Comment by protonmeacc** [comment]
> Без прокси все работает, но хотелось бы более качественную версию

so maybe the problem is in your proxy and not in the script

**Comment by Litva63** [comment]
> > Без прокси все работает, но хотелось бы более качественную версию
> 
> так что, возможно, проблема в вашем прокси, а не в скрипте

прокси исправно, проверял

**Comment by BroPanda** [comment]
у меня тоже прокси поотлетали причем разные, если юзать проексиваер или телеграме - то все ок, как только через бот, не конектится и сплошные ошибки

**Comment by AlexKrutoy** [comment]
Беда с тем, как ты вставляешь прокси, зайди в чат и кинь скрин с пингом @pakistankiller
