### ISSUE TITLE
Pls update script

### ISSUE THREAD

**Issue by mMdooD** [HiddenCodeDevs/BlumTelegramBot#52]
Hi bro blum has updated and gives dogs. Please update the script

**Comment by 0xTaaa** [comment]
> Hi bro blum has updated and gives dogs. Please update the script

cant play game🥲

**Comment by jason866695** [comment]
> > Hi bro blum has updated and gives dogs. Please update the script
> 
> cant play game🥲

same problem

**Comment by Mr-Mk7** [comment]
please update
