### ISSUE TITLE
Update the damn repo

### ISSUE THREAD

**Issue by AminSiddika** [HiddenCodeDevs/BlumTelegramBot#55]
Blum changed Play API Into V2 
Payload changed a bit also...

Upgrade Your Repo Plz..

**Comment by dhvendev** [comment]
Upgrade your repo pls

**Comment by oboroccv** [comment]
Upgrade your repo pls

**Comment by Willian-Massao** [comment]
core/tapper.py line 473

change
resp = await http_client.post(f"{self.game_url}/api/v1/game/play", ssl=False)
to 
resp = await http_client.post(f"{self.game_url}/api/v2/game/play", ssl=False)

**Comment by dhvendev** [comment]
Game/play is easy, game/claim?
Payload encrypt?

**Comment by Willian-Massao** [comment]
Idk, only the game/play is broken for me. For now the change works fine, i will debug more later to see the game/claim

**Comment by revansyahallam** [comment]
> core/tapper.py line 473
> 
> change resp = await http_client.post(f"{self.game_url}/api/v1/game/play", ssl=False) to resp = await http_client.post(f"{self.game_url}/api/v2/game/play", ssl=False)
> 
> for now this fix the playAPI

thanks, it works now bro

**Comment by Niyaz-Mahmud** [comment]
> core/tapper.py line 473
> 
> change resp = await http_client.post(f"{self.game_url}/api/v1/game/play", ssl=False) to resp = await http_client.post(f"{self.game_url}/api/v2/game/play", ssl=False)
> 
> for now this fix the playAPI






It plays game...but no points get added. i had 70k blum points..after playing 26 play passes..its still 70k..

**Comment by nguyenanh29** [comment]
Please! It cannot play game any more

**Comment by jason866695** [comment]
> > core/tapper.py line 473
> > change resp = await http_client.post(f"{self.game_url}/api/v1/game/play", ssl=False) to resp = await http_client.post(f"{self.game_url}/api/v2/game/play", ssl=False)
> > for now this fix the playAPI
> 
> It plays game...but no points get added. i had 70k blum points..after playing 26 play passes..its still 70k..

same problem

**Comment by 0xaust1n** [comment]
> > > core/tapper.py line 473
> > > change resp = await http_client.post(f"{self.game_url}/api/v1/game/play", ssl=False) to resp = await http_client.post(f"{self.game_url}/api/v2/game/play", ssl=False)
> > > for now this fix the playAPI
> > 
> > 
> > It plays game...but no points get added. i had 70k blum points..after playing 26 play passes..its still 70k..
> 
> same problem

Same here. lost like 100 tickets Orz.

**Comment by MorinCerber** [comment]
> How to FIX? 

Тут 70% комьюнити юзающие этот бот - русские, что мы на английском то балакаем 

А так есть вопрос, в папке с ботом с чем нибудь баловался? 
Может имя менял

**Comment by VadimTikh** [comment]
> А так есть вопрос, в папке с ботом с чем нибудь баловался? Может имя менял

Они внедрили функцию хеширования тела запроса на получение поинтов (завершение игры). Судя по всему, это функцию работает на клиенте, очень похоже, что это и есть защита от таких как мы. Возможно, кто-то сможет найти и написать эту функцию, тогда бот снова заработает

**Comment by dhvendev** [comment]
На клиенте написан у них шифратор, в js у них есть интересные строчки с генерацией, ворд листы, вещественные рандомные числа, возвращают шиффразу. В сам payload они залили еще один параметр нагрузки и после ее шифруют фразой, время потратил, стало не интересно копаться дальше, мб кто-то и отыщет алгоритм)

**Comment by Willian-Massao** [comment]
> > How to FIX?
> 
> Тут 70% комьюнити юзающие этот бот - русские, что мы на английском то балакаем
> 
> А так есть вопрос, в папке с ботом с чем нибудь баловался? Может имя менял

i am brazilian srry

**Comment by Daku-coder178** [comment]
yep i have updated and forked the repo. I have the also put an pull request. https://github.com/Daku-coder178/BlumTelegramBot

**Comment by 9ft6** [comment]
> yep i have updated and forked the repo. I have the also put an pull request. https://github.com/Daku-coder178/BlumTelegramBot

Anyone tryed this solution? i tried implement this in my project but failed.

**Comment by vaultboyportal** [comment]
> yep i have updated and forked the repo. I have the also put an pull request. https://github.com/Daku-coder178/BlumTelegramBot

can you share the change here..fork not found

**Comment by XPacL** [comment]
Да он там обосрался, ничего не работает, ещё и рефку свою в код вписал. К успеху шёл, но не фартануло.

**Comment by vaultboyportal** [comment]
the only working script: https://github.com/vaultboyportal/blumNEW
it use a server for the payload

**Comment by 0xaust1n** [comment]
this should be close 
the latest version wroks rn
