### ISSUE TITLE
manage multithread

### ISSUE THREAD

**Issue by anandku93765** [HiddenCodeDevs/BlumTelegramBot#59]
like if i have 1000 session file i dont want to run all at once because if i do account ban chnances are high make code as in sessions folder i will have 1000 session file but at time of run ask like how much session in batch i want to run if i put 50 

it means perform daily task and other operations on 50 account fhirst hold for other 950 accounts 
and after complete all task in 50 account stop those account and go for next 50 and so on 

in 1 ip 1000 account at same time can be banned 
but in 1 ip 50 account at same time wont ban personal expirence

please do so next time

**Comment by gtxPrime** [comment]
> like if i have 1000 session file i dont want to run all at once because if i do account ban chnances are high make code as in sessions folder i will have 1000 session file but at time of run ask like how much session in batch i want to run if i put 50
> 
> it means perform daily task and other operations on 50 account fhirst hold for other 950 accounts and after complete all task in 50 account stop those account and go for next 50 and so on
> 
> in 1 ip 1000 account at same time can be banned but in 1 ip 50 account at same time wont ban personal expirence
> 
> please do so next time

Use Proxy for 1000 accounts, even 50 accounts with same IP will cause you ban
