### ISSUE TITLE
cannot decrypt claim payload

### ISSUE THREAD

**Issue by sudo-feaskic** [HiddenCodeDevs/BlumTelegramBot#62]
Couldn't play game, msg: {"message":"cannot decrypt claim payload"} play_passes: 61

**Comment by KirMozor** [comment]
same thing

**Comment by makesappy** [comment]
same thing.

**Comment by LeifJG** [comment]
same thing

**Comment by ArthurKoba** [comment]
Was fixed in #69

**Comment by AntiWarforever** [comment]
> Was fixed in #69

How to fix problem to pay? Don't work..
What must to do?

**Comment by ArthurKoba** [comment]
> > Was fixed in #69
> 
> How to fix problem to pay? Don't work.. What must to do?

Я не понимаю с какой оплатой у вас проблемы. Бот играет в игры бесплатно на основе локального веб сервера, платить ни за что не нужно.
