### ISSUE TITLE
Error occurred during claim game: list index out of range

### ISSUE THREAD

**Issue by lyaxsh** [HiddenCodeDevs/BlumTelegramBot#63]
![image](https://github.com/user-attachments/assets/e4a8f161-e7e3-4eab-b0d7-50f4e959873c)

**Comment by braveltd** [comment]
because https://raw.githubusercontent.com/zuydd/database/main/blum.json don't have any payloadServer at the moment

**Comment by ivan52605** [comment]
Тут дело видно в коде Блум хорошо зашифровал. Всё

**Comment by ivan52605** [comment]
> потому что https://raw.githubusercontent.com/zuydd/database/main/blum.json на данный момент не имеет payloadServer

Абсолютно такая же история хотя сервера есть

**Comment by braveltd** [comment]
> Тут дело видно в коде Блум хорошо зашифровал. Всё

как я понял этот пэйлоад генерится на клиенте, тоесть нужно разобраться как блюм генерит этот пэйлоад.

на выходе base64 но он зашифрован и/или просто непонятная кодировка

**Comment by ArthurKoba** [comment]
Was fixed in #69
