### ISSUE TITLE
why don’t you update your bot??? If you are so much busy then why you uploaded it?? Remove it please or update. Already one weeks gone, you didn’t show any kind of response 😑

### ISSUE THREAD

**Issue by likhon321** [HiddenCodeDevs/BlumTelegramBot#67]

**Comment by d3signersol** [comment]
Did you pay him? So entitled for a free stuff. At least, the daily claim works, so you can accumulate tickets until a new version is out.

**Comment by likhon321** [comment]
No need... Iam using a different script, which has pyrogram session and drop game is working smoothly 🙂

**Comment by likhon321** [comment]
knock me in tg @likhonxyz

**Comment by d3signersol** [comment]
Done
