### ISSUE TITLE
JWT Token Renewal and Session Management Issues Causing Service Failure and Event Loop Closure

### ISSUE THREAD

**Issue by devrabie** [HiddenCodeDevs/BlumTelegramBot#70]
Issue Description: During the program’s runtime, several issues related to obtaining a new JWT token and managing sessions in aiohttp cause the service to fail and the event loop to close unexpectedly. The following errors appear in the log:

Error obtaining JWT token: Error messages such as "Can't get new token, trying again" appear when attempting to renew the token.

Error in daily_reward_is_available check: An exception occurs when the response is {'message': 'Invalid jwt token'}.

Session and connector closure issues: Unclosed aiohttp sessions and connectors result in warnings such as Unclosed client session and Unclosed connector.

RuntimeError: Event loop is closed: This error occurs when trying to run new tasks on a closed event loop.

Additional Information:

The code relies on asyncio for managing concurrent tasks and aiohttp for handling connections.

The program appears to run as a persistent service with periodically renewed sessions.
![Uploading Screenshot_٢٠٢٤-١١-٠٢-١٩-٠٩-٣٧-٤٢٠_com.server.auditor.ssh.client.jpg…]()

**Comment by ArthurKoba** [comment]
Fixed in #74
