### ISSUE TITLE
Er0r

### ISSUE THREAD

**Issue by AntiWarforever** [HiddenCodeDevs/BlumTelegramBot#72]
While the bot to try doing a task, like a task that have transaction, get bug(always rotating loading) and we can't do transaction manually forever
I try transaction in another device but don't work too
How can fix?
Do you can setup a options(enable or disable) that don't complate the special tasks?

**Comment by ArthurKoba** [comment]
Бот не выполняет специальных задач, он ограничен только задачами типа "SOCIAL_SUBSCRIPTION", "INTERNAL", "SOCIAL_MEDIA_CHECK", которые может запускать. Но забирать награды он может с задач любого типа, подтверждать задачи только с кодовым словом и только при наличии его в базе.

Нужно больше информации о проблеме, о какой конкретно задаче идет речь. (название, раздел)

**Comment by AntiWarforever** [comment]
> The bot does not perform special tasks, it is limited only to tasks of the type "SOCIAL_SUBSCRIPTION", "INTERNAL", "SOCIAL_MEDIA_CHECK", which it can launch. But it can collect rewards from tasks of any type, confirm tasks only with a code word and only if it is in the database.
> 
> More information is needed about the problem, what specific task is being discussed. (title, section)
![Screenshot_2024-11-03-20-37-58-901_com polestar super clone-edit](https://github.com/user-attachments/assets/68d48474-9d32-438a-93cf-fc6c25d6ba13)
When click on this, don't let me to transaction

**Comment by ArthurKoba** [comment]
> ا> Бот не выполняет специальных задач, он ограничен только задачами типа "SOCIAL_SUBSCRIPTION", "INTERNAL", "SOCIAL_MEDIA_CHECK", которые он может запустить. Но он может собирать награды с задач любого типа, подтверждать задачи только кодовым словом и только если оно есть в базе данных.
> 
> > Требуется больше информации о проблеме, какая конкретно задача обсуждается. (название, раздел) 
> > При нажатии на это, не пускайте меня к транзакции 
> > Я использую версию вашего бота ILD, которая делает это и получает ошибку 
> > Я жду неделю и не исправляю

Эта проблема вызвана не ботом, а ошибками разработчиков Blum. Исправить это могут помочь только разработчики игры, проблема находится на их стороне. Бот получает точно такое же состояние ошибки, как и вы в игре, он не может на это повлиять.

**Comment by ArthurKoba** [comment]
https://t.me/blumcrypto/366

The Open League Quest is temporarily paused. 
Read more why:
_To help the TON Blockchain network recover quicker, we'll temporarily disable one of the tasks inside The Open League Quest. We're in touch with the TON team and will resume as soon as possible._
