### ISSUE TITLE
 ERROR  | Payload server not available, maybe offline. Using url: http://localhost:9876

### ISSUE THREAD

**Issue by devrabie** [HiddenCodeDevs/BlumTelegramBot#76]
2024-11-03 06:10:18 | ERROR | @abdakrim1 | Payload server not available, maybe offline. Using url: http://localhost:9876

**Comment by devrabie** [comment]
Is the server run separately or what and how is that done?

**Comment by mask-sir** [comment]
> Is the server run separately or what and how is that done?

How do we run that server separately

**Comment by ArthurKoba** [comment]
https://github.com/HiddenCodeDevs/BlumTelegramBot/blob/main/PAYLOAD-SERVER.MD
