### ISSUE TITLE
Unknown game data structure. Say developers for this!

### ISSUE THREAD

**Issue by Micky-Fan** [HiddenCodeDevs/BlumTelegramBot#80]
### Steps Taken:
1. I pulled the latest code from [KobaProduction/BlumPayloadGenerator](https://github.com/KobaProduction/BlumPayloadGenerator).
2. I followed the setup instructions to run the project as a server.
3. update `CUSTOM_PAYLOAD_SERVER_URL` and `USE_CUSTOM_PAYLOAD_SERVER` in the env.
4. Run clicker 

then I got this error

```
2024-11-06 17:33:26 | ERROR | test-click | STOP PLAYING GAMES! Unknown game data structure. Say developers for this!
2024-11-06 17:33:26 | INFO | test-click | Started playing game. Sleep 37s...
```

**Comment by garnatka** [comment]
same

**Comment by ArthurKoba** [comment]
fixed
