### ISSUE TITLE
403 error

### ISSUE THREAD

**Issue by ksardsas2015** [HiddenCodeDevs/BlumTelegramBot#85]
Stop Tapper. Reason: 403, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url='https://user-domain.blum.codes/api/v1/auth/provider/PROVIDER_TELEGRAM_MINI_APP'

**Comment by kaskabayev** [comment]
same issue

**Comment by vitosrapala** [comment]
та же проблема

**Comment by darhanger** [comment]
same

**Comment by mrjonesdev** [comment]
I have the same error

**Comment by creativebluecat** [comment]
same error

**Comment by polstar11** [comment]
Он фиксить проблему собирается,или он пропал?

**Comment by TheMeror** [comment]
Same

**Comment by YoussefAneflous** [comment]
Same issue.

**Comment by xupeng9** [comment]
how to fix

**Comment by Typ3DHard** [comment]
same

**Comment by ArthurKoba** [comment]
> Он фиксить проблему собирается,или он пропал?

Я не пропал, но и проблему фиксить не собираюсь. Я больше не верю в данный проект и скорее всего дальнейшее развитие бота если и будет происходить, то без моего участия.

**Comment by lelicopter** [comment]
> > Он фиксить проблему собирается,или он пропал?
> 
> Я не пропал, но и проблему фиксить не собираюсь. Я больше не верю в данный проект и скорее всего дальнейшее развитие бота если и будет происходить, то без моего участия.

Дождался бы когда откроют вывод. Дальше стало бы понятно в части профита и целесообразности продолжения поддержки?

![{BFC857EF-0328-4DF5-9BE4-88A898E6D9C6}](https://github.com/user-attachments/assets/c1940636-1103-4966-b2b5-f6c3a36c4150)

**Comment by ArthurKoba** [comment]
> 
> Дождался бы когда откроют вывод. Дальше стало бы понятно в части профита и целесообразности продолжения поддержки?
> 
> ![{BFC857EF-0328-4DF5-9BE4-88A898E6D9C6}](https://github.com/user-attachments/assets/c1940636-1103-4966-b2b5-f6c3a36c4150)
> 
Я уверен на 90 процентов, что все, кто использовали данного бота будут побриты. Разработчики Blum добавили несколько закладок, которые не обходились ботом и все аккаунты помечены. Я именно поэтому и прекратил разработку, не вижу смысла тратить время на нулевой результат. И ответственность за это не только на мне, но и на предыдущих разработчиках, которые не сделали обход прошлых закладок, а также на тех, кто использовали бота. За бесплатное использование никто ничего никому не должен, к боту как обычные пользователи имеют доступ, так и разработчики Blum, которые и встраивали закладки под проект. Используйте платные решения, но я думаю уже поздно...
